apiVersion: v1
kind: Pod
metadata:
  name: storage-pod
spec:
  containers:
  - name: storage-pod
    image: ubuntu
    command: ["/bin/bash", "-ec", "while :; do sleep 2; done"]
    volumeMounts:
    - name: test-csi
      mountPath: /data
  volumes:
  - name: test-csi
    persistentVolumeClaim:
      claimName: storage-pvc